// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD06zIdIK13Qk04kN9cMpkOskduFI4MfI8',
    appId: '1:805471326179:web:08b2eb67fab9a26e8d1ad6',
    messagingSenderId: '805471326179',
    projectId: 'chat-app-5b5ad',
    authDomain: 'chat-app-5b5ad.firebaseapp.com',
    storageBucket: 'chat-app-5b5ad.appspot.com',
    measurementId: 'G-NKHQ6TJQNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMMd5R3dI0INe2DElhIqm5EnMGJowMTs',
    appId: '1:805471326179:android:87903a30cd0695168d1ad6',
    messagingSenderId: '805471326179',
    projectId: 'chat-app-5b5ad',
    storageBucket: 'chat-app-5b5ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxh90uz7njsiXOMu6R3IY1zeUS91VZYw',
    appId: '1:805471326179:ios:a1894bdf53bb49308d1ad6',
    messagingSenderId: '805471326179',
    projectId: 'chat-app-5b5ad',
    storageBucket: 'chat-app-5b5ad.appspot.com',
    iosBundleId: 'com.example.flutterUdemyTharwat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzxh90uz7njsiXOMu6R3IY1zeUS91VZYw',
    appId: '1:805471326179:ios:2b251e60989864e98d1ad6',
    messagingSenderId: '805471326179',
    projectId: 'chat-app-5b5ad',
    storageBucket: 'chat-app-5b5ad.appspot.com',
    iosBundleId: 'com.example.flutterUdemyTharwat2.RunnerTests',
  );
}
